server:
  port: 8080

spring:
  application:
    name: Producer-Service

producer-proxy:
  url:
    log: http://localhost:8081/api/proxy/logs
    ping: http://localhost:8081/api/proxy/ping

app:
  logging:
    # Required by LogService constructor
    levels: INFO,ERROR,DEBUG

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.example.DataStreamX: DEBUG